name: remote_winery
description: "An application to store you wine collection and to see details about the bottles."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  sqflite: ^2.3.3
  path: ^1.9.0
  characters: ^1.3.0
  clock: ^1.1.1
  collection: ^1.19.0
  intl: ^0.19.0
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  string_scanner: ^1.3.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
